version: '3.6'

services:
  nginx:
    image: nginx:1.15.1-alpine
    ports:
      - ${DOCKER_NGINX_PORT}:80
    volumes:
      - type: bind
        source: ./docker/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./docker/localhost.crt
        target: /etc/nginx/ssl/localhost.crt
        read_only: true
      - type: bind
        source: ./docker/localhost.key
        target: /etc/nginx/ssl/localhost.key
        read_only: true
      - ./:/var/www/html # add :cached if on Mac OS
    depends_on:
      - fpm
    networks:
      - netw

  fpm:
    build:
      context: ./
      dockerfile: ./docker/fpm.Dockerfile
    environment:
      XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST}
      PHP_IDE_CONFIG: serverName=localhost
    volumes:
      - ./:/var/www/html # add :cached if on Mac OS
      - ~/.composer:/.composer
    depends_on:
      - db
    user: ${UID}
    networks:
      - netw

  db:
      image: postgres:13.3
      user: root
      working_dir: /var/www/application
      volumes:
          - ./:/var/www/application
          - ./docker/db:/var/lib/postgresql/data
      environment:
          - POSTGRES_USER=${DB_USERNAME}
          - POSTGRES_PASSWORD=${DB_PASSWORD}
          - POSTGRES_DB=${DB_DATABASE}
          - PGDATA=/tmp
      ports:
          - "${DOCKER_POSTGRES_EXTERNAL_PORT}:5432"
      restart: always
      networks:
          - netw

  adminer:
    image: adminer
    ports:
      - 8090:8080
    networks:
      - netw

networks:
  netw:
