version: '3.6'

services:
  nginx:
    image: nginx:1.15.1-alpine
    ports:
      - 7001:80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./localhost.crt
        target: /etc/nginx/ssl/localhost.crt
        read_only: true
      - type: bind
        source: ./localhost.key
        target: /etc/nginx/ssl/localhost.key
        read_only: true
      - ../../:/var/www/html # add :cached if on Mac OS
    depends_on:
      - fpm
      - laravel_echo_server
    networks:
      - flor

  fpm:
    build:
      context: ./
      dockerfile: fpm.Dockerfile
    environment:
      XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST}
      PHP_IDE_CONFIG: serverName=localhost
    volumes:
      - ../../:/var/www/html # add :cached if on Mac OS
      - ~/.composer:/.composer
    depends_on:
      - db
      - redis
    user: ${UID}
    networks:
      - flor

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_flor:/var/lib/mysql
      - ../../database/dumps:/dump
    networks:
      - flor


  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080
    networks:
      - flor

  redis:
    image: redis:5.0-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis:/data
    networks:
      - flor


  laravel_echo_server:
    build:
      context: ./
      dockerfile: laravel-echo-server.Dockerfile
    ports:
      - 6001:6001
    volumes:
      - ../../laravel-echo-server.json:/home/laravel-echo-server/laravel-echo-server.json # add :cached if on Mac OS
    depends_on:
      - redis
    networks:
      - flor

  adminer:
    image: adminer
    ports:
      - 8090:8080
    networks:
      - flor

networks:
  flor:

volumes:
  db_flor:
  redis:
